name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy pytz
      - name: Run pipeline tests
        run: python test_pipeline.py
      - name: Run enhanced quality tests
        run: python test_enhanced_quality.py
